### ISSUE TITLE
Add command jugc prototype

### ISSUE THREAD

**Issue by yamasakih** [yamasakih/jugc#1]

**Comment by yamasakih** [comment]
Created `calculate_descs.py` that written below script:

```python
import os

from jug import barrier, TaskGenerator, value
import pandas as pd
from rdkit import Chem, RDConfig

from jugc import calculate_descriptors

calculate_descriptors = TaskGenerator(calculate_descriptors)

input_file = os.path.join(
    RDConfig.RDDataDir, 'NCI', 'first_200.props.sdf')
supp = Chem.SDMolSupplier(input_file)
mols = [mol for mol in supp]
descs = [calculate_descriptors(mol) for mol in mols]

barrier()

descs = pd.concat(value(descs))
descs.to_csv('descs.csv', index=False)
```

And run following jug command:

```shell
jug execute calculate_descs.py &
jug execute calculate_descs.py &
```

It worked by using two cpus.

**Comment by yamasakih** [comment]
So, my idea:

Create and register jugc.py like below script:

```python
tempdir = ...
for _ in n_cpus:
    subcommand : jug execute calculate_descs.py --jugdir tempdir
```

**Comment by yamasakih** [comment]
How to make temporary directory reference https://qiita.com/everylittle/items/aa7c6f612ff0a9db7f01 (in Japanese).

**Comment by yamasakih** [comment]
Raised error when `python run.py`

```python
% python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import subprocess
  File "/Users/yamasakih/repositories/jugc/jugc/subprocess.py", line 20, in <module>
    barrier()
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/jug/barrier.py", line 82, in barrier
    if not _can_load_limit_recursion(t, alltasks):
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/jug/barrier.py", line 44, in _can_load_limit_recursion
    return t.can_load()
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/jug/task.py", line 244, in can_load
    return store.can_load(self.hash())
AttributeError: 'NoneType' object has no attribute 'can_load'
```

**Comment by yamasakih** [comment]
I can change `barrier()` and `value()` to `bvalue()`

https://jug.readthedocs.io/en/latest/barrier.html#bvalue

**Comment by yamasakih** [comment]
`jug.jug.execution_loop` can execute jug in python code.  
Ref. https://github.com/luispedro/jug/blob/b32f4389acd1c3edf1a6a593799e853ded7849a2/jug/jug.py#L119

**Comment by yamasakih** [comment]
Closes #11

**Comment by yamasakih** [comment]
Checked what dose cmdapi receive as options.

Added `print(opts)` in SubCommandManager class and printed out.

```python
class SubCommandManager:
    def __init__(self):
        self._commands = SubCommandDict()
        self.default_options = Options(None)

    def _register(self, name, cmd_instance):
        if name in self._commands and self._commands[name] != cmd_instance:
            logging.warning("Jug: command: '%s' will be overriden with code from '%s'",
                            name, cmd_instance.__class__.__name__)

        self._commands[name] = cmd_instance

    def update_defaults(self, name):
        cmd = self.get(name)
        opts = cmd.parse_defaults()
        print(opts)
        if opts is not None:
            self.default_options.update(opts)
```

```shell
% jug execute jugc/subprocess.py None
None
{'cleanup_keep_locks': False, 'cleanup_locks_only': False}
None
None
{'execute_keep_going': False, 'execute_target': None, 'execute_wait_cycle_time': 12, 'execute_nr_wait_cycles': 150}
{'graph_no_status': False, 'graph_format': 'png'}
None
None
None
{'status_cache': False, 'status_cache_clear': False, 'status_cache_file': '.jugstatus.sqlite3'}
None
```

**Comment by yamasakih** [comment]
Add debug write to `jug.py`

```python
def main(argv=None):
    global _is_jug_running
    _is_jug_running = True
    from .options import parse
    if argv is None:
        from sys import argv
    print(argv)
    options = parse()
    print('options')
    print(options)
    print(options.__dict__)
    jugspace = None
    store = None
```

Then, it outputed it.

```shell
% jug execute jugc/subprocess.py
['/Users/yamasakih/anaconda3/envs/dev_jugc/bin/jug', 'execute', 'jugc/subprocess.py']
options
<jug.options.Options object at 0x1051867f0>
{'next': <jug.options.Options object at 0x1051864a8>, '_autoinit': False, 'subcommand': 'execute', 'jugfile': 'jugc/subprocess.py', 'aggressive_unload': False, 'short': False, 'pdb': False, 'debug': False, 'user_args': [], 'jugdir': 'jugc/subprocess.jugdata'}
```

**Comment by yamasakih** [comment]
Add debug write to `jug.py`

```python
def execution_loop(tasks, options):
    from time import sleep
    print('In execution_loop')
    print(options)
    print(options.__dict__)
    logging.info('Execute start (%s tasks)' % len(tasks))
```

Then, it outputed following lines:

```shell
% jug execute subprocess.py                                                                                                           (git)-[feature/Create-jguc-command]
['/Users/yamasakih/anaconda3/envs/dev_jugc/bin/jug', 'execute', 'subprocess.py']
options
<jug.options.Options object at 0x10710c1d0>
{'next': <jug.options.Options object at 0x10710c208>, '_autoinit': False, 'subcommand': 'execute', 'jugfile': 'subprocess.py', 'aggressive_unload': False, 'short': False, 'pdb': False, 'debug': False, 'user_args': [], 'jugdir': 'subprocess.jugdata'}
In execution_loop
<jug.options.Options object at 0x10710c1d0>
{'next': <jug.options.Options object at 0x10710c208>, '_autoinit': False, 'subcommand': 'execute', 'jugfile': 'subprocess.py', 'aggressive_unload': False, 'short': False, 'pdb': False, 'debug': False, 'user_args': [], 'jugdir': 'subprocess.jugdata'}
```

`execution_loop` got same `Option` object to `options = parse()` object.

**Comment by yamasakih** [comment]
I will see `test_jug_exection.py` in `jug/jug/tests` to understand how to use `exectuion_loop`.

**Comment by yamasakih** [comment]
All tasks were calculated and result were in `dict_store` in test.  

`dict_store` class is implemented in `jug/backends/dict_store`.

**Comment by yamasakih** [comment]
```python
for key in store.list():
    pass
store.can_load(key)
> True
store.load(key)
> ... # The data what I want to get
```

**Comment by yamasakih** [comment]
Because it is difficult to use execution_loop, I try to execute with jug command yet.

**Comment by yamasakih** [comment]
Add user argument by adding `--` like below:

```shell
% jug execute subprocess.py -- --input test.sdf
```

Ref. https://jug.readthedocs.io/en/latest/faq.html#can-i-pass-command-line-arguments-to-a-jugfile

**Comment by yamasakih** [comment]
Use mktemp command to make temp directory in unix.  

```shell
#!/bin/bash
tmpdir=$(mktemp -d)

echo ${tmpdir}

trap 'rm ${tmpdir}' 0
```

Ref. https://www.kabegiwablog.com/entry/2018/07/04/100000 (In Japanese)

**Comment by yamasakih** [comment]
I want to make this script task, too.

```shell
supp = Chem.SDMolSupplier(input_file)
```

**Comment by yamasakih** [comment]
Use `getopts` command to parse arguments.

Ref. https://qiita.com/laikuaut/items/adf35ecb14c55f6fde92 (In Japanese)

**Comment by yamasakih** [comment]
The following command make temp directory:

```shell
TMPDIR=`mktemp -d ./jugdata.XXXXXX`
```

**Comment by yamasakih** [comment]
It worked. Good work :)
