### ISSUE TITLE
Add jugc command to PyPi packages

### ISSUE THREAD

**Issue by yamasakih** [yamasakih/jugc#13]

**Comment by yamasakih** [comment]
For example, Move `jugc.sh` to `bin` directory and rename `jugc.sh` to `jugc`.

Finally, add `scripts=['bin/jugc']` argument to `setup.py` or `setup.cfg`.

Ref. https://github.com/luispedro/jug/blob/master/bin/jug-execute

**Comment by yamasakih** [comment]
I tried to do the above work.

```shell
% python setup.py install
running install
running bdist_egg
running egg_info
writing jugc.egg-info/PKG-INFO
writing dependency_links to jugc.egg-info/dependency_links.txt
writing top-level names to jugc.egg-info/top_level.txt
reading manifest file 'jugc.egg-info/SOURCES.txt'
writing manifest file 'jugc.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.7
copying bin/jugc -> build/scripts-3.7
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.7/jugc -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.9-x86_64/egg/EGG-INFO/scripts/jugc to 755
copying jugc.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying jugc.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying jugc.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying jugc.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/jugc-0.1.0-py3.7.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing jugc-0.1.0-py3.7.egg
Copying jugc-0.1.0-py3.7.egg to /Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages
Adding jugc 0.1.0 to easy-install.pth file
Installing jugc script to /Users/yamasakih/anaconda3/envs/dev_jugc/bin

Installed /Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/jugc-0.1.0-py3.7.egg
Processing dependencies for jugc==0.1.0
Finished processing dependencies for jugc==0.1.0
```

It copyed `bin/jugc` to `build/scripts-3.7`, so it worked likely.

**Comment by yamasakih** [comment]
Rename `jugc/jugc` to `jugc/jugclib` because the command and package name clash.

Also, change `packages=['jugclib']` in `setup.cfg`.

**Comment by yamasakih** [comment]
Rename `jugc/subprocess.py` to `bin/jugc_subprocess.py`.

**Comment by yamasakih** [comment]
Add `jugc_subprocess.py` to `scripts`:

```
scripts =
  ./bin/jugc
  ./bin/jugc_subprocess.py
```

**Comment by yamasakih** [comment]
jugc_subprocess was not ran by `jugc` command.

```
Traceback (most recent call last):
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/jug/jug.py", line 102, in init
    exec(compile(jfile.read(), jugfile, 'exec'), jugspace, jugspace)
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/bin/jugc_subprocess.py", line 4, in <module>
    __import__('pkg_resources').run_script('jugc==0.1.0b0', 'jugc_subprocess.py')
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/yamasakih/anaconda3/envs/dev_jugc/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/jugc_subprocess.py' not found in metadata at '/Users/yamasakih/repositories/jugc/jugc.egg-info'
```

**Comment by yamasakih** [comment]
`jugc` command file was copied to `~/anaconda3/envs/dev_jugc/bin/jugc`, but `jugc_subprocess.py` was not.  
I think that is the difference between the shell script and pyfile.

```shell
% cat ~/anaconda3/envs/dev_jugc/bin/jugc_subprocess.py #!/Users/yamasakih/anaconda3/envs/dev_jugc/bin/python
# EASY-INSTALL-SCRIPT: 'jugc==0.1.0b0','jugc_subprocess.py'
__requires__ = 'jugc==0.1.0b0'
__import__('pkg_resources').run_script('jugc==0.1.0b0', 'jugc_subprocess.py')
```

**Comment by yamasakih** [comment]
I try to use `entry_points` options.

Ref. https://heavywatal.github.io/python/setuptools.html (In Japanese)

**Comment by yamasakih** [comment]
Added `entry_points.cfg` to `jugc` repository.

```
[console_scripts]
jugc_subprocess.py = jugclib.jugc_subprocess:main
```

removed `scripts=`bin.jugc_subprocess` from `setup.cfg`.

and moved `bin/jugc_subprocess.py` to `jugclib/jugc_subprocess.py`.
